In [ ]:
#Q1 a)
import numpy as np
arr = np.array([1,2,3,6,4,5])
result = arr[::-1]
print(str(result))

[5 4 6 3 2 1]


In [ ]:
#Q1 b)
import numpy as np
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array1.flatten()
array1.ravel()

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [ ]:
#Q1 c)
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
np.array_equal(arr1,arr2)

True

In [ ]:
#Q1 d) i.
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])
y1 = np.bincount(x);
maximum = max(y1);
print(y1.argmax())
m=[]

for i in range(len(y1)):
  if y1[i]==maximum:
    m.append(i)

    for i in range(len(x)):
      for j in range(len(m)):
        if x[i]==m[j]:
          print(m[j]," ",i)

1
1   0
1   5
1   7
1   8
1   9


In [ ]:
#Q1 d) ii.
import numpy as np
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
y1 = np.bincount(y);
maximum = max(y1);
print(y1.argmax())
m=[]

for i in range(len(y1)):
  if y1[i]==maximum:
    m.append(i)

    for i in range(len(y)):
      for j in range(len(m)):
        if y[i]==m[j]:
          print(m[j]," ",i)

1
1   0
1   1
1   2
1   0
1   1
1   2
3   4
3   8
3   9


In [ ]:
#Q1 e) i.
import numpy as np 
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
np.sum(gfg)


45

In [ ]:
#Q1 e) ii.
import numpy as np 
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
np.sum(gfg, axis=1)

matrix([[14],
        [16],
        [15]])

In [ ]:
#Q1 e) iii.
import numpy as np 
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
np.sum(gfg, axis=0)

matrix([[20,  9, 16]])

In [ ]:
#Q1 f) i.
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
trace = np.trace(n_array)
print(trace)

176


In [ ]:
#Q1 f) i. ii.
import numpy as np
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
w, v = np.linalg.eig(n_array)
print("Eigen values of the given array:\n",w)
print("Eigen vectors of the given array:\n",v)

Eigen values of the given array:
 [98.16835147 28.097044   49.73460452]
Eigen vectors of the given array:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [ ]:
#Q1 f) iii.
import numpy as np
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
y = np.linalg.inv(n_array)
print(y)

[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [ ]:
#Q1 f) iv.
import numpy as np
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
y = np.linalg.det(n_array)
print(y)

137180.0000000001


In [ ]:
#Q1 g) i.
import numpy as np
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
res = np.dot(p,q)
print("res is:",res)
np.cov(p,q)

res is: [[16 19]
 [26 31]]


array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

In [ ]:
#Q1 g) ii.
import numpy as np
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
res = np.dot(p,q)
q=np.reshape(q,(3,2))
print("res is:",res)
np.cov(p,q)

res is: [[16 19  5]
 [26 31  8]
 [46 55 14]]


array([[  0.5,   0.5,   0.5,   0.5,   2.5,  -2.5],
       [  0.5,   0.5,   0.5,   0.5,   2.5,  -2.5],
       [  0.5,   0.5,   0.5,   0.5,   2.5,  -2.5],
       [  0.5,   0.5,   0.5,   0.5,   2.5,  -2.5],
       [  2.5,   2.5,   2.5,   2.5,  12.5, -12.5],
       [ -2.5,  -2.5,  -2.5,  -2.5, -12.5,  12.5]])

In [ ]:
#Q1 h) 
import numpy as np
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
a = np.inner(x,y)
print("inner product is ",x)
b = np.outer(x,y)
print("outer product is ",b)
c = np.cross(x,y)
print("cartesian product is",c)

inner product is  [[2 3 4]
 [3 2 9]]
outer product is  [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
cartesian product is [[-20   4   7]
 [-84  36  20]]


In [ ]:
#Q2 a) i. 
import numpy as np
array = np.array([[1, -2, 3],[-4, 5, -6]])
res = np.absolute(array)
print(res)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Q2 a) ii.
import numpy as np
arr = np.array([[1, -2, 3],[-4, 5, -6]])

In [ ]:
# Percentile of the flattened array
print("25th Percentile of arr ",np.percentile(arr, 25))
print("50th Percentile of arr ",np.percentile(arr, 50))
print("75th Percentile of arr ",np.percentile(arr, 75))

25th Percentile of arr  -3.5
50th Percentile of arr  -0.5
75th Percentile of arr  2.5


In [ ]:
# Percentile of each column
print("25th Percentile of arr ",np.percentile(arr, 25, axis =0))
print("50th Percentile of arr ",np.percentile(arr, 50, axis =0))
print("75th Percentile of arr ",np.percentile(arr, 75, axis =0))

25th Percentile of arr  [-2.75 -0.25 -3.75]
50th Percentile of arr  [-1.5  1.5 -1.5]
75th Percentile of arr  [-0.25  3.25  0.75]


In [ ]:

# Percentile of each row
print("25th Percentile of arr ",np.percentile(arr, 25, axis =1))
print("50th Percentile of arr ",np.percentile(arr, 50, axis =1))
print("75th Percentile of arr ",np.percentile(arr, 75, axis =1))

25th Percentile of arr  [-0.5 -5. ]
50th Percentile of arr  [ 1. -4.]
75th Percentile of arr  [2.  0.5]


In [ ]:
#Q2 a) iii.
import numpy as np
arr = np.array([[1, -2, 3],[-4, 5, -6]])

In [ ]:
# Percentile of the flattened array
print("25th mean of arr ",np.mean(arr))
print("50th median of arr ",np.median(arr))
print("75th std of arr ",np.std(arr))
    

25th mean of arr  -0.5
50th median of arr  -0.5
75th std of arr  3.8622100754188224


In [ ]:
# Percentile of each column
print("25th mean of arr ",np.mean(arr, axis =0))
print("50th median of arr ",np.median(arr, axis =0))
print("75th std of arr ",np.std(arr, axis =0))

25th mean of arr  [-1.5  1.5 -1.5]
50th median of arr  [-1.5  1.5 -1.5]
75th std of arr  [2.5 3.5 4.5]


In [ ]:
# Percentile of each row
print("25th mean of arr ",np.mean(arr, axis =1))
print("50th median of arr ",np.median(arr, axis =1))
print("75th std of arr ",np.std(arr, axis =1))

25th mean of arr  [ 0.66666667 -1.66666667]
50th median of arr  [ 1. -4.]
75th std of arr  [2.05480467 4.78423336]


In [ ]:
#Q2 b)
import numpy as np
x = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
r1 = np.floor(x)
r2 = np.ceil(x)
r3 = np.trunc(x)
r4 = np.around(x)
print("floor: ",r1)
print("ceil:  ",r2)
print("trunc: ",r3)
print("round: ",r4)

floor:  [-2. -2. -1.  0.  1.  1.  3.]
ceil:   [-1. -1. -0.  1.  2.  2.  3.]
trunc:  [-1. -1. -0.  0.  1.  1.  3.]
round:  [-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
#Q3 a) i.
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])
print(np.sort(array))

[ 10  16  16  52  54  62 453]


In [ ]:
#Q3 a) ii.
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])
indices = np.argsort(array)
print(indices)

[0 3 4 1 5 2 6]


In [ ]:
#Q3 a) iii.
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])
array1 = np.sort(array)
print(4, "smallest elements of the array")
print(array1[:4])

4 smallest elements of the array
[10 16 16 52]


In [ ]:
#Q3 a) iv.
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])
array1 = np.sort(array)
print(5, "largest elements of the array")
print(array1[-5:])

5 largest elements of the array
[ 16  52  54  62 453]


In [ ]:
#Q3 b) i.
import numpy as np

def isInt(num):
    return np.equal(np.mod(num, 1), 0)

arr = np.array([1.0, 2.3, 3, 4.0, 4.001])

for num in arr:
    if isInt(num):
        print(num, "is an integer")

1.0 is an integer
3.0 is an integer
4.0 is an integer


In [ ]:
#Q3 b) ii.
import numpy as np

def isfloat(num):
    return np.not_equal(np.mod(num, 1), 0)

arr = np.array([1.0, 2.3, 3, 4.0, 4.001])

for num in arr:
    if isfloat(num):
        print(num, "is an float")

2.3 is an float
4.001 is an float


In [12]:

from PIL import Image
from numpy import asarray

image = Image.open('/Users/chayansinha/Library/Mobile Documents/com~apple~CloudDocs/CLICK ME/IMG_2123.jpg')
numpydata = asarray(image)
  
# summarize some details about the image
print(image.format)
print(image.size)
print(image.mode)
print(numpydata)
A=numpydata.flatten('F')
print(numpydata.flatten('F'))
print(A.size)
file = open("g:\\file1.txt", "w+")
content = str(numpydata)
file.write(content)
file.close()


JPEG
(1024, 1024)
RGB
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
[255 255 255 ... 255 255 255]
3145728
